version: '3.8'
services:
  db:
    image: postgres:16.3-alpine
    container_name: video_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video_nestjs
    restart: always
    env_file:
      - docker.env
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  postgres_data:
